### PR TITLE
refactor Spree::Chimpy::SubscribersController#create

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by braidn** [comment]
@krzysiek1507 is this meant for master or a specific branch of spree?

**Comment by krzysiek1507** [comment]
@braidn this PR is against master

**Comment by braidn** [comment]
@krzysiek1507 Yep. However, did you mean to do this against a specific branch so that it works with a specific Spree version?

**Comment by krzysiek1507** [comment]
@braidn Nope. I wanted to add a possibility to update other attributes than `email` and `subscribed`.

**Comment by braidn** [comment]
What were your ideas for other attributes?

**Comment by krzysiek1507** [comment]
@braidn I needed `name`

**Comment by braidn** [comment]
You need name in MailChimp? Could this be added to MailChimp using the merge vars?

**Comment by krzysiek1507** [comment]
@braidn sorry, but I don't remember, it was 6 months ago. I can see we've added `NAME` to merge vars too.

**Pull request closed without merging**
