### PR TITLE
Do not submit orders created via guest checkout

### PR DESCRIPTION
**Pull request by jkelleyj**
We can swap this to the master branch once that's updated.

### CODE REVIEW

**Comment by braidn** [comment]
@jkelleyj I have just updated master and 3-stable. I changed this over to the master branch. Is this still a 👍 ?

**Comment by jkelleyj** [comment]
I'll take a look tonight to be sure.  Thanks for merging.

**Comment by jkelleyj** [comment]
Hey @braidn this is all good to go.  Only change was to require a customer ID for sending an order.  This avoids sending up anonymous checkouts that lack a user_id.  If there were a case to be made for guest checkouts being saved to Mailchimp, I could see refactoring the code to use the actual email of the customer (guest or member) to send to Mailchimp instead of basing it on user_id.  I feel that not sending guest checkouts is more in the spirit of what a guest checkout really is, so this code looks good to me.

**Comment by braidn** [comment]
👍 @jkelleyj merging. I honestly think omitting a guest checkout is a good thing. I am not a fan of them overall.

**Comment by braidn** [comment]
2-stable and 3-stable both have this patch as well.

**Comment by jormon** [comment]
@braidn would you be open to a PR that made the option to upsert guest orders configurable with the default to false?  I think there's a reasonable case to have this functionality, especially when stores set `double_opt_in` to false.

**Comment by braidn** [comment]
Absolutely!

**Pull request merged**
