### PR TITLE
Use V2 of MailChimp API

### PR DESCRIPTION
**Pull request by braidn**
Hey @braidn - 

If you have some time in the next week or so, do you want to take a run at this? We're currently using an old version of the mailchimp gem that communicates with an older (deprecated) version of the API. 

I'd like to upgrade to use https://rubygems.org/gems/mailchimp-api. 

cc: @joshnuss @DynamoMTL/mickeyren

### CODE REVIEW

**Comment by braidn** [comment]
Ok all! I think we are good to move this into master. Everyone's thoughts?

cc: @bryanmtl @joshnuss

**Comment by joshnuss** [comment]
@braidn looks awesome!

huge :+1:

**Comment by braidn** [comment]
Does everyone think that it is ok to operate master at Spree 2.1 and up? and maintain the 1.3 branch?

**Comment by joshnuss** [comment]
Yup, sounds good to me

**Pull request merged**
